### ISSUE TITLE
Unanswered call - talk time incorrect

### ISSUE THREAD

**Issue by l3nz** [KevinRavasi/QueueMetricsWallboard#1]
<img width="1182" alt="screen shot 2015-12-15 at 14 50 11" src="https://cloud.githubusercontent.com/assets/1101849/11812454/485b9b7c-a33c-11e5-9cb1-bd9432307e5a.png">

The conversation time for the wallboard appears incorrect - if there is no conversation time.
Also, the HTML entity ''nbsp'' should be stripped as it is a blank space.

**Comment by KevinRavasi** [comment]
Fixed the answer time bug and added the conversation time field. Tomorrow i will get rid of the nbsp problem! :)

**Comment by KevinRavasi** [comment]
the nbsp issue seems to be fixed :D
