### ISSUE TITLE
Install docs

### ISSUE THREAD

**Issue by l3nz** [KevinRavasi/QueueMetricsWallboard#2]
The README file could do with some cleaning up. It is unclear how one should install this project. Do we need a webserver? can it be run remotely?

**Comment by KevinRavasi** [comment]
I personally use xampp apache http server, thank you for the advice i will work on it!

anyways you can extract the folder in your www folder, edit the address and port parameter in WallBoard.html with a text editor then run chrome.exe --disable-web-security in the command line. When you are done you can open the html page and it should work.

**Comment by l3nz** [comment]
I agree but this is meant as a public project :)

**Comment by KevinRavasi** [comment]
Updated the Readme with images and a more detailed installation procedure. I also implemented a proxy solution for the CORS problem.

**Comment by l3nz** [comment]
:)
